[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
  '@solemate=lib/solemate/src'
]
# used in place of fftrue to let foundry access these folders from terminal
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
